name: flatmates
description: "A flatmates game built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.5+1
  go_router: ^17.3.0
  vector_math: ^2.1.5
  flutter_svg: ^2.0.15+2
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/geometry/prefabs/Cableclamp.obj
    - assets/crafts/
    - assets/crafts/img/
    - assets/crafting_blueprints/house_foo/
    - assets/models/house_foo/steps/
