import 'package:flutter/material.dart';
import 'iso_coordinate.dart';
import 'iso_projection.dart';

/// The eight viewing directions for axonometric view (45-degree steps).
///
/// Cardinal directions (nw, sw, se, ne) produce standard isometric diamonds.
/// Intermediate directions (w, s, e, n) produce military/planometric quads.
///
/// The enum length is tied to [IsoProjection.viewCount]. Expanding to 16
/// values (22.5-degree steps) is straightforward: add 8 more entries and
/// update [IsoProjection.viewCount].
enum IsoViewDirection {
  /// Northwest view (index 0, 0 deg)
  nw,

  /// West view (index 1, 45 deg)
  w,

  /// Southwest view (index 2, 90 deg)
  sw,

  /// South view (index 3, 135 deg)
  s,

  /// Southeast view (index 4, 180 deg)
  se,

  /// East view (index 5, 225 deg)
  e,

  /// Northeast view (index 6, 270 deg)
  ne,

  /// North view (index 7, 315 deg)
  n;

  /// Rotate clockwise to next direction.
  /// Steps through all [values.length] directions.
  IsoViewDirection rotateClockwise() {
    return IsoViewDirection.values[(index + 1) %
        IsoViewDirection.values.length];
  }

  /// Rotate counter-clockwise to previous direction.
  IsoViewDirection rotateCounterClockwise() {
    return IsoViewDirection.values[(index -
            1 +
            IsoViewDirection.values.length) %
        IsoViewDirection.values.length];
  }

  /// Whether this is a cardinal direction (isometric diamond tiles).
  bool get isCardinal => index.isEven;

  /// The nearest cardinal direction index (0-3) for 4-sprite asset lookup.
  ///
  /// Uses: `((index + viewsPerCardinal ~/ 2) ~/ viewsPerCardinal) % 4`
  /// where `viewsPerCardinal = values.length ~/ 4`.
  int get nearestCardinalIndex {
    final vpc = IsoViewDirection.values.length ~/ 4; // 2 for 8-view
    return ((index + vpc ~/ 2) ~/ vpc) % 4;
  }

  /// The rotation angle of this view in radians (includes base angle offset).
  double get angleRad => IsoProjection.angleForView(index);
}

/// Camera for axonometric view with pan, zoom, and discrete rotation
class IsoCamera extends ChangeNotifier {
  IsoCamera({
    Offset? position,
    double zoom = 1.0,
    IsoViewDirection view = IsoViewDirection.nw,
    this.minZoom = 0.3,
    this.maxZoom = 3.0,
  }) : _position = position ?? Offset.zero,
       _zoom = zoom.clamp(0.3, 3.0),
       _view = view;

  Offset _position;
  double _zoom;
  IsoViewDirection _view;

  final double minZoom;
  final double maxZoom;

  /// Camera center position in world space
  Offset get position => _position;
  set position(Offset value) {
    if (_position != value) {
      _position = value;
      notifyListeners();
    }
  }

  /// Zoom level (scale factor)
  double get zoom => _zoom;
  set zoom(double value) {
    final clamped = value.clamp(minZoom, maxZoom);
    if (_zoom != clamped) {
      _zoom = clamped;
      notifyListeners();
    }
  }

  /// Current viewing direction
  IsoViewDirection get view => _view;
  set view(IsoViewDirection value) {
    if (_view != value) {
      _view = value;
      notifyListeners();
    }
  }

  /// World view index matching the current [IsoViewDirection].
  ///
  /// This is simply [_view.index] -- it indexes directly into the list
  /// of world views generated by the sprite system (whose length equals
  /// [IsoViewDirection.values.length], currently 8).
  int get worldViewIndex => _view.index;

  /// The rotation angle of the current view in radians.
  double get angleRad => _view.angleRad;

  /// Pan the camera by a delta in world space
  void pan(Offset delta) {
    position = _position + delta;
  }

  /// Pan the camera by a screen space delta
  /// The delta is automatically rotated based on current view direction
  /// so that pan feels consistent regardless of view angle
  void panScreen(Offset screenDelta) {
    // Rotate the pan delta to match the current view orientation
    final rotatedDelta = _rotatePanDeltaForView(screenDelta);
    final worldDelta = Offset(rotatedDelta.dx / _zoom, rotatedDelta.dy / _zoom);
    pan(worldDelta);
  }

  /// Rotate a screen-space delta to counter the view rotation
  /// This ensures panning feels consistent across all view angles
  Offset _rotatePanDeltaForView(Offset delta) {
    return delta;
  }

  /// Zoom by a factor (1.0 = no change, >1.0 = zoom in, <1.0 = zoom out)
  void zoomBy(double factor) {
    zoom = _zoom * factor;
  }

  /// Zoom by a scroll delta (negative = zoom in, positive = zoom out)
  void zoomByScroll(double scrollDelta) {
    const sensitivity = 0.001;
    final factor = 1.0 - scrollDelta * sensitivity;
    zoomBy(factor);
  }

  /// Rotate to next view clockwise
  void rotateClockwise() {
    view = _view.rotateClockwise();
  }

  /// Rotate to previous view counter-clockwise
  void rotateCounterClockwise() {
    view = _view.rotateCounterClockwise();
  }

  /// Rotate clockwise around the tile currently at the center of the screen.
  /// Steps by 1 through the 8 view directions (45 degrees per press).
  void rotateClockwiseAroundCenter() {
    final centerTile = getCenterTile();

    final newView = _view.rotateClockwise();
    _view = newView;

    if (centerTile != null) {
      _position = IsoProjection.isoToScreen(
        centerTile.x,
        centerTile.y,
        viewIndex: newView.index,
      );
    }

    notifyListeners();
  }

  /// Rotate counter-clockwise around the tile currently at the center.
  void rotateCounterClockwiseAroundCenter() {
    final centerTile = getCenterTile();

    final newView = _view.rotateCounterClockwise();
    _view = newView;

    if (centerTile != null) {
      _position = IsoProjection.isoToScreen(
        centerTile.x,
        centerTile.y,
        viewIndex: newView.index,
      );
    }

    notifyListeners();
  }

  /// Get the tile coordinate at the center of the current view
  IsoCoordinate? getCenterTile() {
    return IsoProjection.screenToIso(_position, viewIndex: _view.index);
  }

  // -- Cached viewport centre to avoid repeated division --
  Size? _cachedVpSize;
  double _vpCenterX = 0;
  double _vpCenterY = 0;

  void _ensureVpCenter(Size viewport) {
    if (viewport != _cachedVpSize) {
      _cachedVpSize = viewport;
      _vpCenterX = viewport.width / 2;
      _vpCenterY = viewport.height / 2;
    }
  }

  /// Convert world coordinates to screen coordinates
  Offset worldToScreen(Offset worldPos, Size viewport) {
    _ensureVpCenter(viewport);
    final dx = worldPos.dx - _position.dx;
    final dy = worldPos.dy - _position.dy;
    return Offset(_vpCenterX + dx * _zoom, _vpCenterY + dy * _zoom);
  }

  /// Convert screen coordinates to world coordinates
  Offset? screenToWorld(Offset screenPos, Size viewport) {
    if (viewport.isEmpty) return null;
    _ensureVpCenter(viewport);

    final worldOffset = Offset(
      (screenPos.dx - _vpCenterX) / _zoom,
      (screenPos.dy - _vpCenterY) / _zoom,
    );
    return _position + worldOffset;
  }

  /// Focus camera on a specific world position (instant, no animation).
  /// For animated panning, use an external AnimationController driving
  /// [position] via a Tween.
  void focusOn(Offset target) {
    position = target;
  }

  /// Get the world-space bounds visible in the current viewport
  Rect getVisibleWorldBounds(Size viewport) {
    if (viewport.isEmpty) {
      return Rect.fromLTWH(_position.dx, _position.dy, 0, 0);
    }

    final halfWidth = viewport.width / 2 / _zoom;
    final halfHeight = viewport.height / 2 / _zoom;

    return Rect.fromCenter(
      center: _position,
      width: halfWidth * 2,
      height: halfHeight * 2,
    );
  }

  @override
  String toString() {
    return 'IsoCamera(pos: $_position, zoom: ${_zoom.toStringAsFixed(2)}, view: $_view)';
  }
}
